//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INFOSiS_2._0.DAServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", ConfigurationName="DAServer.Server")]
    public interface Server {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/InsertInterestedRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/InsertInterestedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(person))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        INFOSiS_2._0.DAServer.InsertInterestedResponse InsertInterested(INFOSiS_2._0.DAServer.InsertInterestedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/InsertInterestedRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/InsertInterestedResponse")]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.InsertInterestedResponse> InsertInterestedAsync(INFOSiS_2._0.DAServer.InsertInterestedRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/InsertProfessorRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/InsertProfessorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(person))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        INFOSiS_2._0.DAServer.InsertProfessorResponse InsertProfessor(INFOSiS_2._0.DAServer.InsertProfessorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/InsertProfessorRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/InsertProfessorResponse")]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.InsertProfessorResponse> InsertProfessorAsync(INFOSiS_2._0.DAServer.InsertProfessorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllByCourseRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllByCourseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(person))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        INFOSiS_2._0.DAServer.QueryAllByCourseResponse QueryAllByCourse(INFOSiS_2._0.DAServer.QueryAllByCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllByCourseRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllByCourseResponse")]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllByCourseResponse> QueryAllByCourseAsync(INFOSiS_2._0.DAServer.QueryAllByCourseRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllUsersRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllUsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(person))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        INFOSiS_2._0.DAServer.QueryAllUsersResponse QueryAllUsers(INFOSiS_2._0.DAServer.QueryAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllUsersRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllUsersResponse")]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllUsersResponse> QueryAllUsersAsync(INFOSiS_2._0.DAServer.QueryAllUsersRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/VerifyUserRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/VerifyUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(person))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        INFOSiS_2._0.DAServer.VerifyUserResponse VerifyUser(INFOSiS_2._0.DAServer.VerifyUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/VerifyUserRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/VerifyUserResponse")]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.VerifyUserResponse> VerifyUserAsync(INFOSiS_2._0.DAServer.VerifyUserRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllInterestedRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllInterestedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(person))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        INFOSiS_2._0.DAServer.QueryAllInterestedResponse QueryAllInterested(INFOSiS_2._0.DAServer.QueryAllInterestedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllInterestedRequest", ReplyAction="http://server.INFOSiS.pucp.edu.pe/Server/QueryAllInterestedResponse")]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllInterestedResponse> QueryAllInterestedAsync(INFOSiS_2._0.DAServer.QueryAllInterestedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class interested : person {
        
        private int idField;
        
        private course[] coursesField;
        
        private bool isUnsubscribedField;
        
        private string emailPUCPField;
        
        private System.DateTime regDateField;
        
        private bool regDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public course[] courses {
            get {
                return this.coursesField;
            }
            set {
                this.coursesField = value;
                this.RaisePropertyChanged("courses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isUnsubscribed {
            get {
                return this.isUnsubscribedField;
            }
            set {
                this.isUnsubscribedField = value;
                this.RaisePropertyChanged("isUnsubscribed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string emailPUCP {
            get {
                return this.emailPUCPField;
            }
            set {
                this.emailPUCPField = value;
                this.RaisePropertyChanged("emailPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime regDate {
            get {
                return this.regDateField;
            }
            set {
                this.regDateField = value;
                this.RaisePropertyChanged("regDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regDateSpecified {
            get {
                return this.regDateFieldSpecified;
            }
            set {
                this.regDateFieldSpecified = value;
                this.RaisePropertyChanged("regDateSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class course : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private bool isActiveField;
        
        private courseType courseTypeField;
        
        private string descriptionField;
        
        private string syllabusField;
        
        private course[] courseHistoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("isActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public courseType courseType {
            get {
                return this.courseTypeField;
            }
            set {
                this.courseTypeField = value;
                this.RaisePropertyChanged("courseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string syllabus {
            get {
                return this.syllabusField;
            }
            set {
                this.syllabusField = value;
                this.RaisePropertyChanged("syllabus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseHistory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public course[] courseHistory {
            get {
                return this.courseHistoryField;
            }
            set {
                this.courseHistoryField = value;
                this.RaisePropertyChanged("courseHistory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class courseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private course[] coursesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coursesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public course[] coursesList {
            get {
                return this.coursesListField;
            }
            set {
                this.coursesListField = value;
                this.RaisePropertyChanged("coursesList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class userType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string usernameField;
        
        private string passwordField;
        
        private userType accesField;
        
        private bool isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public userType acces {
            get {
                return this.accesField;
            }
            set {
                this.accesField = value;
                this.RaisePropertyChanged("acces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("isActive");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(professor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(interested))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idNumberField;
        
        private int idTypeField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string primaryLastNameField;
        
        private string secondLastNameField;
        
        private string genderField;
        
        private string emailField;
        
        private string cellPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
                this.RaisePropertyChanged("idNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
                this.RaisePropertyChanged("idType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("middleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primaryLastName {
            get {
                return this.primaryLastNameField;
            }
            set {
                this.primaryLastNameField = value;
                this.RaisePropertyChanged("primaryLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string secondLastName {
            get {
                return this.secondLastNameField;
            }
            set {
                this.secondLastNameField = value;
                this.RaisePropertyChanged("secondLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
                this.RaisePropertyChanged("cellPhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/")]
    public partial class professor : person {
        
        private string idPUCPField;
        
        private string emailPUCPField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private course[] coursesCanTeachField;
        
        private bool isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idPUCP {
            get {
                return this.idPUCPField;
            }
            set {
                this.idPUCPField = value;
                this.RaisePropertyChanged("idPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string emailPUCP {
            get {
                return this.emailPUCPField;
            }
            set {
                this.emailPUCPField = value;
                this.RaisePropertyChanged("emailPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
                this.RaisePropertyChanged("birthDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coursesCanTeach", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public course[] coursesCanTeach {
            get {
                return this.coursesCanTeachField;
            }
            set {
                this.coursesCanTeachField = value;
                this.RaisePropertyChanged("coursesCanTeach");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("isActive");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertInterested", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertInterestedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.interested interested;
        
        public InsertInterestedRequest() {
        }
        
        public InsertInterestedRequest(INFOSiS_2._0.DAServer.interested interested) {
            this.interested = interested;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertInterestedResponse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertInterestedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public InsertInterestedResponse() {
        }
        
        public InsertInterestedResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertProfessor", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertProfessorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.professor professor;
        
        public InsertProfessorRequest() {
        }
        
        public InsertProfessorRequest(INFOSiS_2._0.DAServer.professor professor) {
            this.professor = professor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertProfessorResponse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertProfessorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public InsertProfessorResponse() {
        }
        
        public InsertProfessorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllByCourse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class QueryAllByCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.course course;
        
        public QueryAllByCourseRequest() {
        }
        
        public QueryAllByCourseRequest(INFOSiS_2._0.DAServer.course course) {
            this.course = course;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllByCourseResponse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class QueryAllByCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.interested[] @return;
        
        public QueryAllByCourseResponse() {
        }
        
        public QueryAllByCourseResponse(INFOSiS_2._0.DAServer.interested[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllUsers", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class QueryAllUsersRequest {
        
        public QueryAllUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllUsersResponse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class QueryAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.user[] @return;
        
        public QueryAllUsersResponse() {
        }
        
        public QueryAllUsersResponse(INFOSiS_2._0.DAServer.user[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUser", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class VerifyUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.user user;
        
        public VerifyUserRequest() {
        }
        
        public VerifyUserRequest(INFOSiS_2._0.DAServer.user user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUserResponse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class VerifyUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.userType @return;
        
        public VerifyUserResponse() {
        }
        
        public VerifyUserResponse(INFOSiS_2._0.DAServer.userType @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllInterested", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class QueryAllInterestedRequest {
        
        public QueryAllInterestedRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllInterestedResponse", WrapperNamespace="http://server.INFOSiS.pucp.edu.pe/", IsWrapped=true)]
    public partial class QueryAllInterestedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.INFOSiS.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INFOSiS_2._0.DAServer.interested[] @return;
        
        public QueryAllInterestedResponse() {
        }
        
        public QueryAllInterestedResponse(INFOSiS_2._0.DAServer.interested[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServerChannel : INFOSiS_2._0.DAServer.Server, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerClient : System.ServiceModel.ClientBase<INFOSiS_2._0.DAServer.Server>, INFOSiS_2._0.DAServer.Server {
        
        public ServerClient() {
        }
        
        public ServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INFOSiS_2._0.DAServer.InsertInterestedResponse INFOSiS_2._0.DAServer.Server.InsertInterested(INFOSiS_2._0.DAServer.InsertInterestedRequest request) {
            return base.Channel.InsertInterested(request);
        }
        
        public int InsertInterested(INFOSiS_2._0.DAServer.interested interested) {
            INFOSiS_2._0.DAServer.InsertInterestedRequest inValue = new INFOSiS_2._0.DAServer.InsertInterestedRequest();
            inValue.interested = interested;
            INFOSiS_2._0.DAServer.InsertInterestedResponse retVal = ((INFOSiS_2._0.DAServer.Server)(this)).InsertInterested(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.InsertInterestedResponse> INFOSiS_2._0.DAServer.Server.InsertInterestedAsync(INFOSiS_2._0.DAServer.InsertInterestedRequest request) {
            return base.Channel.InsertInterestedAsync(request);
        }
        
        public System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.InsertInterestedResponse> InsertInterestedAsync(INFOSiS_2._0.DAServer.interested interested) {
            INFOSiS_2._0.DAServer.InsertInterestedRequest inValue = new INFOSiS_2._0.DAServer.InsertInterestedRequest();
            inValue.interested = interested;
            return ((INFOSiS_2._0.DAServer.Server)(this)).InsertInterestedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INFOSiS_2._0.DAServer.InsertProfessorResponse INFOSiS_2._0.DAServer.Server.InsertProfessor(INFOSiS_2._0.DAServer.InsertProfessorRequest request) {
            return base.Channel.InsertProfessor(request);
        }
        
        public int InsertProfessor(INFOSiS_2._0.DAServer.professor professor) {
            INFOSiS_2._0.DAServer.InsertProfessorRequest inValue = new INFOSiS_2._0.DAServer.InsertProfessorRequest();
            inValue.professor = professor;
            INFOSiS_2._0.DAServer.InsertProfessorResponse retVal = ((INFOSiS_2._0.DAServer.Server)(this)).InsertProfessor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.InsertProfessorResponse> INFOSiS_2._0.DAServer.Server.InsertProfessorAsync(INFOSiS_2._0.DAServer.InsertProfessorRequest request) {
            return base.Channel.InsertProfessorAsync(request);
        }
        
        public System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.InsertProfessorResponse> InsertProfessorAsync(INFOSiS_2._0.DAServer.professor professor) {
            INFOSiS_2._0.DAServer.InsertProfessorRequest inValue = new INFOSiS_2._0.DAServer.InsertProfessorRequest();
            inValue.professor = professor;
            return ((INFOSiS_2._0.DAServer.Server)(this)).InsertProfessorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INFOSiS_2._0.DAServer.QueryAllByCourseResponse INFOSiS_2._0.DAServer.Server.QueryAllByCourse(INFOSiS_2._0.DAServer.QueryAllByCourseRequest request) {
            return base.Channel.QueryAllByCourse(request);
        }
        
        public INFOSiS_2._0.DAServer.interested[] QueryAllByCourse(INFOSiS_2._0.DAServer.course course) {
            INFOSiS_2._0.DAServer.QueryAllByCourseRequest inValue = new INFOSiS_2._0.DAServer.QueryAllByCourseRequest();
            inValue.course = course;
            INFOSiS_2._0.DAServer.QueryAllByCourseResponse retVal = ((INFOSiS_2._0.DAServer.Server)(this)).QueryAllByCourse(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllByCourseResponse> INFOSiS_2._0.DAServer.Server.QueryAllByCourseAsync(INFOSiS_2._0.DAServer.QueryAllByCourseRequest request) {
            return base.Channel.QueryAllByCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllByCourseResponse> QueryAllByCourseAsync(INFOSiS_2._0.DAServer.course course) {
            INFOSiS_2._0.DAServer.QueryAllByCourseRequest inValue = new INFOSiS_2._0.DAServer.QueryAllByCourseRequest();
            inValue.course = course;
            return ((INFOSiS_2._0.DAServer.Server)(this)).QueryAllByCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INFOSiS_2._0.DAServer.QueryAllUsersResponse INFOSiS_2._0.DAServer.Server.QueryAllUsers(INFOSiS_2._0.DAServer.QueryAllUsersRequest request) {
            return base.Channel.QueryAllUsers(request);
        }
        
        public INFOSiS_2._0.DAServer.user[] QueryAllUsers() {
            INFOSiS_2._0.DAServer.QueryAllUsersRequest inValue = new INFOSiS_2._0.DAServer.QueryAllUsersRequest();
            INFOSiS_2._0.DAServer.QueryAllUsersResponse retVal = ((INFOSiS_2._0.DAServer.Server)(this)).QueryAllUsers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllUsersResponse> INFOSiS_2._0.DAServer.Server.QueryAllUsersAsync(INFOSiS_2._0.DAServer.QueryAllUsersRequest request) {
            return base.Channel.QueryAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllUsersResponse> QueryAllUsersAsync() {
            INFOSiS_2._0.DAServer.QueryAllUsersRequest inValue = new INFOSiS_2._0.DAServer.QueryAllUsersRequest();
            return ((INFOSiS_2._0.DAServer.Server)(this)).QueryAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INFOSiS_2._0.DAServer.VerifyUserResponse INFOSiS_2._0.DAServer.Server.VerifyUser(INFOSiS_2._0.DAServer.VerifyUserRequest request) {
            return base.Channel.VerifyUser(request);
        }
        
        public INFOSiS_2._0.DAServer.userType VerifyUser(INFOSiS_2._0.DAServer.user user) {
            INFOSiS_2._0.DAServer.VerifyUserRequest inValue = new INFOSiS_2._0.DAServer.VerifyUserRequest();
            inValue.user = user;
            INFOSiS_2._0.DAServer.VerifyUserResponse retVal = ((INFOSiS_2._0.DAServer.Server)(this)).VerifyUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.VerifyUserResponse> INFOSiS_2._0.DAServer.Server.VerifyUserAsync(INFOSiS_2._0.DAServer.VerifyUserRequest request) {
            return base.Channel.VerifyUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.VerifyUserResponse> VerifyUserAsync(INFOSiS_2._0.DAServer.user user) {
            INFOSiS_2._0.DAServer.VerifyUserRequest inValue = new INFOSiS_2._0.DAServer.VerifyUserRequest();
            inValue.user = user;
            return ((INFOSiS_2._0.DAServer.Server)(this)).VerifyUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INFOSiS_2._0.DAServer.QueryAllInterestedResponse INFOSiS_2._0.DAServer.Server.QueryAllInterested(INFOSiS_2._0.DAServer.QueryAllInterestedRequest request) {
            return base.Channel.QueryAllInterested(request);
        }
        
        public INFOSiS_2._0.DAServer.interested[] QueryAllInterested() {
            INFOSiS_2._0.DAServer.QueryAllInterestedRequest inValue = new INFOSiS_2._0.DAServer.QueryAllInterestedRequest();
            INFOSiS_2._0.DAServer.QueryAllInterestedResponse retVal = ((INFOSiS_2._0.DAServer.Server)(this)).QueryAllInterested(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllInterestedResponse> INFOSiS_2._0.DAServer.Server.QueryAllInterestedAsync(INFOSiS_2._0.DAServer.QueryAllInterestedRequest request) {
            return base.Channel.QueryAllInterestedAsync(request);
        }
        
        public System.Threading.Tasks.Task<INFOSiS_2._0.DAServer.QueryAllInterestedResponse> QueryAllInterestedAsync() {
            INFOSiS_2._0.DAServer.QueryAllInterestedRequest inValue = new INFOSiS_2._0.DAServer.QueryAllInterestedRequest();
            return ((INFOSiS_2._0.DAServer.Server)(this)).QueryAllInterestedAsync(inValue);
        }
    }
}
